use_frameworks!

platform :ios, '8.0'

target 'LXCImagePickerManager_Example' do
  pod 'LXCImagePickerManager', :path => '../'

  target 'LXCImagePickerManager_Tests' do
    inherit! :search_paths

    
  end
end
